<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>com.levis9527</groupId>
        <artifactId>jfs</artifactId>
        <version>0.1.0-SNAPSHOT</version>
    </parent>
    <artifactId>jfs-store</artifactId>
    <name>jfs-store</name>
    <description>Physical small-file storage: needle, volume, index</description>
    <dependencies>
        <dependency>
            <groupId>com.levis9527</groupId>
            <artifactId>jfs-common</artifactId>
        </dependency>
    </dependencies>
</project>
